update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  lane :unittests do
  scan(
    device: "iPhone 16",
    clean: true,
    scheme: "LeafTimer"
  )
  end

  lane :beta do
    unittests

    increment_build_number
    commit_version_bump(xcodeproj: "LeafTimer.xcodeproj")
    push_to_git_remote

    build_app(workspace: "LeafTimer.xcworkspace", scheme: "LeafTimer Release")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end