platform :ios, '17.0'
use_frameworks!
inhibit_all_warnings!

target 'LeafTimer' do

  # Pods for LeafTimer - Updated for iOS 17 and Xcode 15
  pod 'Firebase/Analytics', '~> 10.0'
  pod 'Google-Mobile-Ads-SDK', '~> 11.0'

  target 'LeafTimerTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    pod 'ViewInspector'
  end

  target 'LeafTimerUITests' do
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
